name: Deploy to GitHub Pages
run-name: pages build and deployment
on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
 deploy:
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - run: quarto render rapport.ipynb --output index.html
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
